export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAIL = 'BOTAO_CLICADO_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_UPDATE_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CREATE_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const ALUNO_UPDATE_SUCCESS = 'REGISTER_SUCCESS';
export const Aluno_CREATE_SUCCESS = 'REGISTER_SUCCESS';
export const ALUNO_REQUEST = 'REGISTER_REQUEST';
export const ALUNO_FAIL = 'REGISTER_FAIL';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
